(() => {
'use strict';
if(window.__FROMAGO_LOCATIONS_UI_V11__)return;
window.__FROMAGO_LOCATIONS_UI_V11__=true;
const DATA=window.FROMAGO_GEO_DATA;if(!DATA)return;
const GEO=DATA.points,GALLERIES=DATA.galleries;
function codeFor(a){const l=String(a?.location||'');if(l.startsWith('Escenario Can Bech'))return'L01';if(l.startsWith('Trascastillo · Bestiarium'))return'L02';if(l.startsWith('Carpa Sabor a Málaga'))return'L03';if(l.startsWith('Palacio de la Encarnación'))return'L04';if(l.startsWith('Escenario Cobadú'))return'L05';if(l.startsWith('Escenario PanFest'))return'L06';if(l.startsWith('Escenario Caja Rural'))return'L07';if(l.startsWith('Escenario Troncoso Privée'))return'L08';if(l.startsWith('Espacio Zamora es Calidad'))return'L09';if(l.startsWith('Vaca Vallelongo'))return'L10';if(l.startsWith('Plaza de los Animales'))return'L11';if(l.startsWith('Stand 141-142 Diputación de Zamora'))return'L12';if(l.startsWith('Escenario EILZA'))return'L13';if(l.startsWith('Stand DOP Queso Zamorano'))return'L14';if(l.startsWith('Iglesia de San Cipriano'))return'L15';if(l.startsWith('Iglesia de San Juan de Puerta Nueva'))return'L16';if(l.startsWith('Plaza de la Lana'))return'L17';if(l.startsWith('Zona PanFest'))return'L18';if(l.startsWith('Teatro Ramos Carrión'))return'L19';if(l.startsWith('Plaza de la Constitución'))return'L20';if(l.startsWith('Plaza de los Momos'))return'L21';if(l.startsWith('Pasacalles por el recorrido'))return'L22';if(l.startsWith('Galerías del queso'))return'L23';return null}
function pointFor(a){const c=codeFor(a);return c&&GEO[c]?GEO[c]:null}
function openPoint(p){window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${p.lat},${p.lng}`)}`,'_blank','noopener')}
window.openGeoGallery=i=>{const p=GALLERIES[+i];if(p)openPoint(p)};
window.openMaps=function(id){const a=ACTIVITIES.find(x=>x.id===+id);if(!a)return;const c=codeFor(a);if(c==='L22'||c==='L23')return;const p=pointFor(a);if(p)openPoint(p);else if(typeof toast==='function')toast('Ubicación pendiente de validar')};
const style=document.createElement('style');style.textContent='.routebox,.multiloc{margin:10px 0;border:1px solid var(--line);border-radius:12px;padding:10px;background:#fff;font-size:11px;line-height:1.45}.multilocgrid{display:grid;gap:6px;margin-top:8px}.maprow{display:flex;gap:8px;align-items:center;justify-content:space-between}.maprow span{font-size:10px}.maprow button{white-space:nowrap}';document.head.appendChild(style);
function safe(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function routeFrom(s=''){const m=String(s).match(/Recorrido:\s*(.*?)(?:\s*·\s*Organiza:|$)/i);return m?m[1].trim():''}
function organiserFrom(s=''){const m=String(s).match(/·\s*Organiza:\s*(.*)$/i);return m?m[1].trim():''}
function enhanceDetail(id){const a=ACTIVITIES.find(x=>x.id===+id),card=document.querySelector('#detailOverlay .detailcard');if(!a||!card)return;const code=codeFor(a),actions=card.querySelector('.detailactions'),mapButton=actions?[...actions.querySelectorAll('button')].find(b=>b.textContent.includes('Ver ubicación')):null;if(code==='L22'){mapButton?.remove();const route=routeFrom(a.details);if(route&&!card.querySelector('.routebox')){const box=document.createElement('div');box.className='routebox';box.innerHTML=`<b>🚶 Recorrido del pasacalles</b><br>${safe(route)}`;const txt=card.querySelector('.detailtext');if(txt){const org=organiserFrom(a.details);if(org)txt.textContent=`Organiza: ${org}`;else txt.remove()}actions?.before(box)}return}if(code==='L23'){mapButton?.remove();if(!card.querySelector('.multiloc')){const box=document.createElement('div');box.className='multiloc';box.innerHTML=`<b>📍 Cuatro galerías</b><div class="multilocgrid">${GALLERIES.map((p,i)=>`<div class="maprow"><span>${safe(p.name)}</span><button class="tiny" onclick="openGeoGallery(${i})">Abrir mapa</button></div>`).join('')}</div>`;actions?.before(box)}return}if(!pointFor(a))mapButton?.remove()}
const oldOpen=window.openActivity;if(typeof oldOpen==='function')window.openActivity=function(id){oldOpen(id);setTimeout(()=>enhanceDetail(id),0)};
function cachedWants(){const rid=new URL(location.href).searchParams.get('room');if(!rid)return[];try{const d=JSON.parse(localStorage.getItem(`fromago-v11-cache:${rid}`)||'null');if(!d)return[];if(Array.isArray(d.my_preferences))return d.my_preferences.filter(p=>p.level==='want').map(p=>+p.id);return Array.isArray(d.my_selections)?d.my_selections.map(Number):[]}catch(e){return[]}}
function samePoint(a,b){const x=pointFor(a),y=pointFor(b);if(!x||!y)return null;return x.lat===y.lat&&x.lng===y.lng}
function accurateTravelWarnings(){document.querySelectorAll('.travwarn').forEach(x=>x.remove());const ids=new Set(cachedWants());if(!ids.size)return;for(const day of DAY_ORDER){const arr=ACTIVITIES.filter(a=>ids.has(a.id)&&a.day===day&&a.time!=='Todo el día'&&pointFor(a)).sort(sortActs);for(let i=0;i<arr.length-1;i++){const a=arr[i],b=arr[i+1],base=a.end?mins(a.end):mins(a.time),sb=mins(b.time);if(base==null||sb==null||samePoint(a,b)!==false)continue;const gap=sb-base;if(gap<0||gap>state.buffer)continue;const tiles=[...document.querySelectorAll('.plantile')],ta=tiles.find(x=>x.getAttribute('onclick')===`openActivity(${a.id})`),tb=tiles.find(x=>x.getAttribute('onclick')===`openActivity(${b.id})`);if(ta){const w=document.createElement('div');w.className='travwarn';w.textContent=`🚶 Siguiente en otro espacio (${gap} min)`;ta.appendChild(w)}if(tb){const w=document.createElement('div');w.className='travwarn';w.textContent=`🚶 Cambio de espacio: ${gap} min entre horarios`;tb.appendChild(w)}}}}
const oldFav=window.renderFavorites;if(typeof oldFav==='function')window.renderFavorites=function(){oldFav();accurateTravelWarnings()};
setTimeout(()=>{if(document.querySelector('.dayboard'))accurateTravelWarnings()},100);
window.FROMAGO_GEO={codeFor,pointFor,GEO,GALLERIES};
})();
