(() => {
'use strict';
if(window.__FROMAGO_V10__) return;
window.__FROMAGO_V10__=true;
const APP_VERSION='10.0.0';
const params=new URL(location.href).searchParams;
const roomId=params.get('room');
let inviteKey=params.get('k');
let client=null,roomData=null,roomSig='',adminData=null,loading=false,pollTimer=null;
let meId=null,mySecret=null,ownerSecret=null;
const DEVICE_KEY='fromago-secure-device-v1';
const CAT_KEY='fromago-v10-categories';
const DAY_KEY='fromago-v10-myday';
const ALL_GROUPS=GROUPS.filter(g=>g!=='Todo');
const key=s=>roomId?`fromago-secure-${s}:${roomId}`:`fromago-secure-${s}`;
function rnd(){const a=new Uint8Array(32);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
function deviceSecret(){let x=localStorage.getItem(DEVICE_KEY);if(!x){x=rnd();localStorage.setItem(DEVICE_KEY,x)}return x}
function loadCreds(){if(!roomId)return;meId=localStorage.getItem(key('participant-id'));mySecret=localStorage.getItem(key('participant-secret'));ownerSecret=localStorage.getItem(key('owner-secret'))}
loadCreds();
let enabledGroups;try{const x=JSON.parse(localStorage.getItem(CAT_KEY)||'null');enabledGroups=new Set(Array.isArray(x)?x.filter(g=>ALL_GROUPS.includes(g)):ALL_GROUPS.filter(g=>g!=='Profesional'))}catch(e){enabledGroups=new Set(ALL_GROUPS.filter(g=>g!=='Profesional'))}
if(!enabledGroups.size)enabledGroups=new Set(ALL_GROUPS.filter(g=>g!=='Profesional'));
let myDay=localStorage.getItem(DAY_KEY)||DAY_ORDER[0];

const css=document.createElement('style');css.textContent=`
:root{--v10red:#fff0ee;--v10green:#eaf7f1;--v10amber:#fff7d6}
.securebar{margin:8px 0;padding:7px 9px;border:1px solid var(--line);border-left:3px solid var(--green);border-radius:10px;background:var(--greenbg);font-size:11px;line-height:1.35}.securebar.warn{border-left-color:var(--warn);background:var(--warnbg)}
.card{padding:10px 11px;margin:6px 0;border-radius:14px}.title{font-size:14px;margin:6px 0 5px}.meta{font-size:11px}.details{font-size:11px;margin-top:5px}.actions{margin-top:7px;align-items:center}.badge{font-size:9px;padding:4px 6px}.time{font-size:12px}
.heartbtn{width:34px;height:34px;border-radius:50%;border:1px solid var(--line);background:#fff;font-size:20px;display:grid;place-items:center;padding:0;flex:0 0 34px}.heartbtn.on{background:var(--ink);color:#fff;border-color:var(--ink)}
.matchbadge{display:inline-flex;align-items:center;gap:3px;background:var(--greenbg);color:var(--green);border:1px solid #b9e3d3;border-radius:999px;padding:4px 7px;font-size:10px;font-weight:850}.matchnames{font-size:10px;color:var(--green);font-weight:750}
.planhead{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:8px 0}.planhead h2{font-size:16px;margin:0}.summarystrip{display:flex;gap:6px;overflow:auto;margin:7px 0}.summarypill{white-space:nowrap;background:#fff;border:1px solid var(--line);border-radius:999px;padding:5px 8px;font-size:10px;font-weight:800}.summarypill.good{background:var(--greenbg);color:var(--green);border-color:#b9e3d3}.summarypill.bad{background:var(--dangerbg);color:var(--danger);border-color:#f2c6c1}.summarypill.warn{background:var(--warnbg);color:var(--warn);border-color:#edd27e}
.mydaychips{display:flex;gap:6px;overflow:auto;margin:7px 0 9px}.mydaychip{border:1px solid var(--line);background:#fff;border-radius:999px;padding:6px 9px;font-size:11px;font-weight:800;white-space:nowrap}.mydaychip.active{background:var(--ink);color:#fff;border-color:var(--ink)}
.dayboard{background:#fff;border:1px solid var(--line);border-radius:14px;overflow:hidden}.planrow{display:grid;grid-template-columns:58px 1fr;border-top:1px solid var(--line);min-height:48px}.planrow:first-child{border-top:0}.plantime{padding:9px 5px;text-align:center;font-size:11px;font-weight:900;background:#fffaf0}.planitems{display:grid;grid-template-columns:repeat(auto-fit,minmax(125px,1fr));gap:5px;padding:5px}.plantile{position:relative;border:1px solid var(--line);background:#fff;border-radius:9px;padding:7px 26px 7px 8px;min-height:38px;text-align:left;cursor:pointer}.plantile.hard{background:var(--v10red);border-color:#e8877e}.plantile.soft{background:var(--v10amber);border-color:#edd27e}.plantile.match{box-shadow:inset 3px 0 0 var(--green)}.plantitle{font-size:11px;font-weight:850;line-height:1.2;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.plansub{font-size:9px;color:var(--muted);margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tilecount{position:absolute;right:5px;top:5px;min-width:18px;height:18px;border-radius:999px;background:var(--danger);color:#fff;font-size:9px;font-weight:900;display:grid;place-items:center;padding:0 4px}.tilematch{position:absolute;right:5px;bottom:5px;font-size:10px}.emptyday{padding:28px 16px;text-align:center;color:var(--muted);font-size:12px}
.detailback{position:fixed;inset:0;background:rgba(10,10,10,.68);z-index:9999;display:flex;align-items:flex-end;justify-content:center}.detailcard{width:min(620px,100%);max-height:82vh;overflow:auto;background:#fffaf0;border-radius:20px 20px 0 0;padding:18px;box-shadow:0 -18px 60px rgba(0,0,0,.24)}.detailcard h2{font-size:19px;margin:8px 0}.detailclose{float:right;border:1px solid var(--line);background:#fff;border-radius:999px;width:34px;height:34px;font-weight:900}.detailmeta{font-size:12px;color:var(--muted);line-height:1.5}.detailtext{font-size:13px;line-height:1.5;margin:10px 0}.detailmatches{background:var(--greenbg);border:1px solid #b9e3d3;border-radius:10px;padding:9px;font-size:11px;color:var(--green);margin-top:10px}
.joinback{position:fixed;inset:0;background:rgba(10,10,10,.68);z-index:9999;display:flex;align-items:center;justify-content:center;padding:18px}.joincard{width:min(440px,100%);background:#fffaf0;border-radius:20px;padding:20px}.joincard h2{margin:7px 0 6px}.joincard p{font-size:12px;line-height:1.5;color:var(--muted)}.joinrow{display:flex;gap:8px;margin-top:13px}.joinrow input{min-width:0;flex:1;border:1px solid var(--line);border-radius:11px;padding:11px 12px;font:inherit}.joinrow button{border:0;background:var(--cheese);border-radius:11px;padding:10px 13px;font-weight:850}
.adminhero{background:#171717;color:#fff;border-radius:15px;padding:13px;margin:9px 0}.adminhero h2{font-size:16px;margin:0 0 4px}.adminhero p{font-size:11px;color:#d7d2c8;margin:0}.adminstats{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:8px 0}.adminstat{background:#fff;border:1px solid var(--line);border-radius:11px;padding:9px;text-align:center}.adminstat b{display:block;font-size:17px}.adminstat span{font-size:9px;color:var(--muted)}.adminactions{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0}.tiny{border:1px solid var(--line);background:#fff;border-radius:8px;padding:7px 8px;font-size:10px;font-weight:800}.tiny.danger{color:var(--danger)}.adminpeople{background:#fff;border:1px solid var(--line);border-radius:13px;padding:9px;margin:8px 0}.adminrowp{display:grid;grid-template-columns:1fr auto auto;gap:7px;align-items:center;padding:7px 0;border-top:1px solid var(--line)}.adminrowp:first-child{border-top:0}.adminname{font-size:12px;font-weight:850}.adminmeta{font-size:9px;color:var(--muted)}
@media(max-width:480px){.planitems{grid-template-columns:repeat(2,minmax(0,1fr))}.plantile{padding-right:23px}.adminstats{grid-template-columns:repeat(3,1fr)}}
`;document.head.appendChild(css);
document.title='FROMAGO · Mi plan';const h1=document.querySelector('.hero h1');if(h1)h1.textContent='FROMAGO · Plan compartido';

function loadScript(src){return new Promise((ok,bad)=>{const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=bad;document.head.appendChild(s)})}
async function ensureRuntime(){if(client)return client;await loadScript('./sync-config.js?v=10');if(!window.supabase?.createClient)await loadScript('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/dist/umd/supabase.min.js');const c=window.FROMAGO_SYNC;if(!c?.supabaseUrl||!c?.supabaseKey)throw new Error('sync_config');client=window.supabase.createClient(c.supabaseUrl,c.supabaseKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});return client}
function errCode(e){return String(e?.message||e||'').match(/(name_taken|device_already_joined|device_banned|room_locked|room_full|join_rate_limited|room_not_found|invalid_name_length|invalid_name_chars|owner_only|not_your_participant)/)?.[1]||''}
function explain(e){const c=errCode(e);return ({name_taken:'Ese nombre ya está utilizado.',device_already_joined:'Este dispositivo ya tiene un participante.',device_banned:'Este dispositivo fue bloqueado.',room_locked:'Las incorporaciones están cerradas.',room_full:'El grupo está completo.',join_rate_limited:'Demasiadas altas en poco tiempo.',room_not_found:'El enlace ya no es válido.',invalid_name_length:'El nombre debe tener entre 2 y 32 caracteres.',invalid_name_chars:'El nombre contiene caracteres no admitidos.',owner_only:'Acción reservada al propietario.',not_your_participant:'No puedes modificar el plan de otra persona.'}[c]||'No se pudo completar la operación.')}
function me(){return roomData?.participants?.find(p=>p.id===meId)}
function mySelections(){return roomData?.my_selections||[]}
function myHas(id){return mySelections().includes(id)}
function matchesFor(id){return roomData?.matches?.[String(id)]||[]}
function activeMine(){const ids=new Set(mySelections());return ACTIVITIES.filter(a=>ids.has(a.id)).sort(sortActs)}

window.createSecureGroup=async function(){let name=prompt('Tu nombre como creador del grupo');if(name==null)return;name=name.trim();if(!name)return;try{const c=await ensureRuntime(),os=rnd(),ik=rnd(),ps=rnd(),ds=deviceSecret();const {data,error}=await c.rpc('fromago_secure_create_room',{p_owner_secret:os,p_invite_secret:ik,p_device_secret:ds,p_participant_secret:ps,p_name:name});if(error)throw error;const rid=data.room_id,pid=data.participant_id;localStorage.setItem(`fromago-secure-owner-secret:${rid}`,os);localStorage.setItem(`fromago-secure-participant-id:${rid}`,pid);localStorage.setItem(`fromago-secure-participant-secret:${rid}`,ps);const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('room',rid);u.searchParams.set('k',ik);u.searchParams.set('appv','10');location.href=u.toString()}catch(e){toast(explain(e))}}
window.joinSecureGroup=async function(){const inp=document.getElementById('secureName');const name=(inp?.value||'').trim();if(!name)return;try{const c=await ensureRuntime(),ps=rnd();const {data,error}=await c.rpc('fromago_secure_join_room',{p_room_id:roomId,p_invite_secret:inviteKey,p_device_secret:deviceSecret(),p_participant_secret:ps,p_name:name});if(error)throw error;meId=String(data);mySecret=ps;localStorage.setItem(key('participant-id'),meId);localStorage.setItem(key('participant-secret'),mySecret);document.getElementById('joinOverlay')?.remove();await refreshRoom(false);state.view='favorites';save();render()}catch(e){toast(explain(e))}}
function showJoin(){if(!roomId||me()||document.getElementById('joinOverlay')||roomData?.locked)return;const el=document.createElement('div');el.id='joinOverlay';el.className='joinback';el.innerHTML=`<div class="joincard"><span class="badge">INVITACIÓN AL GRUPO</span><h2>Elige tu nombre</h2><p>Tu nombre quedará fijado. Desde este dispositivo solo podrás crear un participante y únicamente modificarás tu propio plan.</p><div class="joinrow"><input id="secureName" maxlength="32" autocomplete="name" placeholder="Tu nombre"><button onclick="joinSecureGroup()">Entrar</button></div></div>`;document.body.appendChild(el);document.getElementById('secureName')?.addEventListener('keydown',e=>{if(e.key==='Enter')joinSecureGroup()})}
window.showSecureJoin=showJoin;

async function refreshRoom(silent=false){if(!roomId||!inviteKey||loading)return false;loading=true;try{const c=await ensureRuntime();let data,error;if(meId&&mySecret){({data,error}=await c.rpc('fromago_v10_get_my_plan',{p_room_id:roomId,p_invite_secret:inviteKey,p_participant_id:meId,p_participant_secret:mySecret}))}else{({data,error}=await c.rpc('fromago_v10_get_public_room',{p_room_id:roomId,p_invite_secret:inviteKey}))}if(error)throw error;const sig=JSON.stringify(data),changed=sig!==roomSig;roomSig=sig;roomData=data;if(!silent||changed)render();if(!me())showJoin();return changed}catch(e){console.error(e);if(!silent)document.getElementById('app').innerHTML=`<div class="empty">${esc(explain(e))}</div>`;return false}finally{loading=false}}
async function refreshAdmin(){if(!ownerSecret||!roomId)return;try{const c=await ensureRuntime();const {data,error}=await c.rpc('fromago_v10_owner_admin',{p_room_id:roomId,p_owner_secret:ownerSecret});if(error)throw error;adminData=data;if(state.view==='itinerary')render()}catch(e){toast(explain(e))}}
async function saveMine(){if(!me()||!mySecret)return;const c=await ensureRuntime();const {error}=await c.rpc('fromago_secure_save_itinerary',{p_room_id:roomId,p_invite_secret:inviteKey,p_participant_id:meId,p_participant_secret:mySecret,p_activity_ids:mySelections()});if(error)throw error}
window.toggleSecureFav=async function(id){if(!me()){showJoin();return}const arr=roomData.my_selections||(roomData.my_selections=[]),i=arr.indexOf(id);i>=0?arr.splice(i,1):arr.push(id);render();try{await saveMine();await refreshRoom(true)}catch(e){toast(explain(e));await refreshRoom(false)}}

function secureNotice(){if(!roomId)return `<div class="securebar warn"><b>Plan compartido privado.</b> Crea un grupo y cada persona gestionará únicamente su selección.</div>`;return `<div class="securebar"><b>● ${me()?esc(me().name):'Plan compartido'}.</b> ${me()?'Tu selección es privada; solo se muestran coincidencias puntuales con otros participantes.':'Únete para crear tu plan.'}</div>`}
function favArea(a){if(!roomId)return `<button class="heartbtn" onclick="event.stopPropagation();createSecureGroup()">♡</button>`;if(!me())return `<button class="heartbtn" onclick="event.stopPropagation();showSecureJoin()">♡</button>`;const on=myHas(a.id),m=matchesFor(a.id);return `<button class="heartbtn ${on?'on':''}" aria-label="${on?'Quitar':'Añadir'}" onclick="event.stopPropagation();toggleSecureFav(${a.id})">${on?'♥':'♡'}</button>${m.length?`<span class="matchbadge">👥 ${m.length+1}</span><span class="matchnames">${m.map(x=>esc(x.name)).join(', ')}</span>`:''}`}
card=function(a,extra=''){return `<article class="card ${a.time==='Todo el día'?'allDay':''}" onclick="openActivity(${a.id})"><div class="topline"><span class="badge">${esc(a.category)}</span><span class="time">${esc(a.time)}${a.end?'–'+esc(a.end):''}</span></div><div class="title">${esc(a.title)}</div><div class="meta"><strong>📍 ${esc(a.location)}</strong>${a.registration?' · ✍️ Inscripción':''}${a.paid?' · 💳 De pago':''}</div>${extra}<div class="actions">${favArea(a)}</div></article>`}

window.toggleCategory=function(g){if(g==='Todo'){enabledGroups=new Set(ALL_GROUPS)}else if(enabledGroups.has(g)){enabledGroups.delete(g)}else enabledGroups.add(g);if(!enabledGroups.size)enabledGroups.add(g);localStorage.setItem(CAT_KEY,JSON.stringify([...enabledGroups]));setupFilters();renderProgram()}
setupFilters=function(){document.getElementById('daychips').innerHTML=['Todos',...DAY_ORDER].map(d=>`<button class="chip ${state.day===d?'active':''}" onclick="state.day='${d}';save();setupFilters();renderProgram()">${d==='Todos'?'Todos':fmtDay(d)}</button>`).join('');document.getElementById('catchips').innerHTML=[`<button class="chip ${enabledGroups.size===ALL_GROUPS.length?'active':''}" onclick="toggleCategory('Todo')">Todas</button>`,...ALL_GROUPS.map(g=>`<button class="chip ${enabledGroups.has(g)?'active':''}" onclick="toggleCategory('${esc(g)}')">${esc(g)}</button>`)].join('');const locs=[...new Set(ACTIVITIES.map(a=>a.location))].sort((a,b)=>a.localeCompare(b,'es'));const sel=document.getElementById('locfilter');sel.innerHTML='<option value="">Todos los espacios</option>'+locs.map(l=>`<option ${state.loc===l?'selected':''}>${esc(l)}</option>`).join('');document.getElementById('search').value=state.query||'';document.getElementById('regOnly').checked=!!state.regOnly}
filtered=function(){const q=(state.query||'').toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu,'');return ACTIVITIES.filter(a=>{const hay=[a.title,a.location,a.details,a.category,a.group].join(' ').toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu,'');return(state.day==='Todos'||a.day===state.day)&&enabledGroups.has(a.group)&&(!q||hay.includes(q))&&(!state.regOnly||a.registration)&&(!state.loc||a.location===state.loc)})}
const baseProgram=renderProgram;renderProgram=function(){baseProgram();document.getElementById('app')?.insertAdjacentHTML('afterbegin',secureNotice())}

function overlapInfo(day){const acts=activeMine().filter(a=>a.day===day&&a.time!=='Todo el día');const hard={},soft={};for(let i=0;i<acts.length;i++)for(let j=i+1;j<acts.length;j++){const x=acts[i],y=acts[j],sx=mins(x.time),sy=mins(y.time);if(sx==null||sy==null)continue;const [a,b,sa,sb]=sx<=sy?[x,y,sx,sy]:[y,x,sy,sx];const ea=a.end?mins(a.end):null;let h=false,s=false;if(sa===sb)h=true;else if(ea!=null&&sb<ea)h=true;else if(sb-sa<state.buffer)s=true;if(h){hard[a.id]=(hard[a.id]||0)+1;hard[b.id]=(hard[b.id]||0)+1}else if(s){soft[a.id]=true;soft[b.id]=true}}return{hard,soft}}
function dayChips(){return `<div class="mydaychips">${DAY_ORDER.map(d=>`<button class="mydaychip ${myDay===d?'active':''}" onclick="setMyDay('${d}')">${fmtDay(d)}</button>`).join('')}</div>`}
window.setMyDay=function(d){myDay=d;localStorage.setItem(DAY_KEY,d);renderFavorites()}
function boardFor(day){const arr=activeMine().filter(a=>a.day===day).sort(sortActs),ov=overlapInfo(day);if(!arr.length)return '<div class="dayboard"><div class="emptyday">No tienes actividades seleccionadas este día.</div></div>';const groups=[];for(const a of arr){let g=groups.find(x=>x.time===a.time);if(!g){g={time:a.time,items:[]};groups.push(g)}g.items.push(a)}return `<div class="dayboard">${groups.map(g=>`<div class="planrow"><div class="plantime">${esc(g.time)}</div><div class="planitems">${g.items.map(a=>{const m=matchesFor(a.id),hard=(ov.hard[a.id]||0)+1;return `<button class="plantile ${ov.hard[a.id]?'hard':ov.soft[a.id]?'soft':''} ${m.length?'match':''}" onclick="openActivity(${a.id})"><span class="plantitle">${esc(a.title)}</span><span class="plansub">${esc(a.location.split('·')[0].trim())}</span>${ov.hard[a.id]?`<span class="tilecount">${hard}</span>`:''}${m.length?`<span class="tilematch">👥${m.length+1}</span>`:''}</button>`}).join('')}</div></div>`).join('')}</div>`}
renderFavorites=function(){document.getElementById('programFilters').style.display='none';if(!roomId){document.getElementById('countpill').textContent='Mi plan';document.getElementById('app').innerHTML=secureNotice()+`<div class="empty"><button class="primary" onclick="createSecureGroup()">Crear grupo compartido</button></div>`;return}if(!roomData){document.getElementById('app').innerHTML='<div class="empty">Cargando…</div>';return}if(!me()){document.getElementById('app').innerHTML=secureNotice()+'<div class="empty">Únete al grupo para crear tu plan.</div>';return}const all=activeMine(),dayActs=all.filter(a=>a.day===myDay),ov=overlapInfo(myDay);const hardCount=new Set(dayActs.filter(a=>ov.hard[a.id]).map(a=>a.id)).size;const matchCount=dayActs.filter(a=>matchesFor(a.id).length).length;document.getElementById('countpill').textContent=`${all.length} elegidas`;document.getElementById('app').innerHTML=secureNotice()+`<div class="planhead"><h2>Mi plan</h2><span class="readonly">Pulsa una actividad para verla completa</span></div>${dayChips()}<div class="summarystrip"><span class="summarypill">${dayActs.length} actividades</span><span class="summarypill good">👥 ${matchCount} coincidencias</span><span class="summarypill ${hardCount?'bad':''}">⛔ ${hardCount} con solape</span><span class="summarypill warn">⏱ margen ${state.buffer} min</span></div>${boardFor(myDay)}<div class="settings"><label>Margen para avisos cercanos <select onchange="state.buffer=+this.value;save();renderFavorites()">${[15,30,45,60,90].map(v=>`<option value="${v}" ${state.buffer===v?'selected':''}>${v} min</option>`).join('')}</select></label></div>`}

window.openActivity=function(id){const a=ACTIVITIES.find(x=>x.id===id);if(!a)return;const m=matchesFor(id),on=myHas(id);const el=document.createElement('div');el.className='detailback';el.id='detailOverlay';el.onclick=e=>{if(e.target===el)el.remove()};el.innerHTML=`<div class="detailcard"><button class="detailclose" onclick="document.getElementById('detailOverlay').remove()">×</button><span class="badge">${esc(a.category)}</span><h2>${esc(a.title)}</h2><div class="detailmeta"><b>${esc(a.day)} · ${esc(a.time)}${a.end?'–'+esc(a.end):''}</b><br>📍 ${esc(a.location)}${a.registration?'<br>✍️ Requiere inscripción':''}${a.paid?'<br>💳 Actividad de pago':''}</div>${a.details?`<div class="detailtext">${esc(a.details)}</div>`:''}${m.length?`<div class="detailmatches"><b>Coincides con ${m.map(x=>esc(x.name)).join(', ')}</b> en esta actividad.</div>`:''}<div class="actions"><button class="heartbtn ${on?'on':''}" onclick="event.stopPropagation();toggleSecureFav(${a.id});document.getElementById('detailOverlay').remove()">${on?'♥':'♡'}</button></div></div>`;document.body.appendChild(el)}

async function renderAdmin(){document.getElementById('programFilters').style.display='none';document.getElementById('countpill').textContent='Admin';if(!ownerSecret){document.getElementById('app').innerHTML='<div class="empty">Administración no disponible en este terminal.</div>';return}if(!adminData)await refreshAdmin();if(!adminData)return;const total=adminData.participants.reduce((s,p)=>s+(p.selection_count||0),0);document.getElementById('app').innerHTML=`<div class="adminhero"><h2>Administración del grupo</h2><p>Separada de tu experiencia como visitante. Aquí gestionas el grupo, no los itinerarios individuales.</p></div><div class="adminstats"><div class="adminstat"><b>${adminData.participants.length}</b><span>Participantes</span></div><div class="adminstat"><b>${total}</b><span>Selecciones totales</span></div><div class="adminstat"><b>${adminData.locked?'Cerrado':'Abierto'}</b><span>Altas</span></div></div><div class="adminactions"><button class="tiny" onclick="shareSecureLink()">Compartir enlace</button><button class="tiny" onclick="ownerToggleLock()">${adminData.locked?'Abrir altas':'Cerrar altas'}</button><button class="tiny" onclick="ownerRotateLink()">Regenerar enlace</button></div><div class="adminpeople">${adminData.participants.map(p=>`<div class="adminrowp"><div><div class="adminname">${esc(p.name)}${p.is_owner?' · propietario':''}</div><div class="adminmeta">${p.selection_count} selecciones · desde ${new Date(p.joined_at).toLocaleDateString('es-ES')}</div></div><span class="readonly">${p.id===meId?'TÚ':''}</span>${!p.is_owner?`<button class="tiny danger" onclick="ownerKick('${esc(p.id)}','${esc(p.name)}')">Expulsar</button>`:''}</div>`).join('')}</div>`}
renderItinerary=function(){renderAdmin()}

window.shareSecureLink=async function(){const u=new URL(location.href);u.searchParams.delete('appv');const data={title:'Plan FROMAGO',text:'Únete al plan compartido y crea tu selección privada.',url:u.toString()};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);toast('Enlace copiado')}}catch(e){}}
window.ownerToggleLock=async function(){try{const c=await ensureRuntime();const locked=adminData?.locked??roomData?.locked;const {error}=await c.rpc('fromago_secure_owner_lock',{p_room_id:roomId,p_owner_secret:ownerSecret,p_locked:!locked});if(error)throw error;await refreshAdmin();await refreshRoom(true)}catch(e){toast(explain(e))}}
window.ownerKick=async function(pid,name){if(!confirm(`¿Expulsar y bloquear a ${name}?`))return;try{const c=await ensureRuntime();const {error}=await c.rpc('fromago_secure_owner_remove_participant',{p_room_id:roomId,p_owner_secret:ownerSecret,p_participant_id:pid});if(error)throw error;await refreshAdmin();await refreshRoom(true)}catch(e){toast(explain(e))}}
window.ownerRotateLink=async function(){if(!confirm('El enlace actual dejará de funcionar. ¿Continuar?'))return;try{const nk=rnd(),c=await ensureRuntime();const {error}=await c.rpc('fromago_secure_owner_rotate_invite',{p_room_id:roomId,p_owner_secret:ownerSecret,p_new_invite_secret:nk});if(error)throw error;inviteKey=nk;const u=new URL(location.href);u.searchParams.set('k',nk);u.searchParams.set('appv','10');history.replaceState(null,'',u);await refreshRoom(false);toast('Enlace regenerado')}catch(e){toast(explain(e))}}

selectedActivities=function(){return activeMine()};personHas=function(pid,id){return pid===meId&&myHas(id)};chosenPeople=function(id){return myHas(id)?[me()?.name||'Yo']:[]};personName=function(){return me()?.name||'Visitante'};
itineraryText=function(){let lines=['🧀 FROMAGO 2026 · Mi plan'],d='';for(const a of activeMine()){if(a.day!==d){d=a.day;lines.push('',`— ${d} —`)}lines.push(`${a.time} · ${a.title} · ${a.location}`)}return lines.join('\n')}

function configureNav(){const nav=[...document.querySelectorAll('.navbtn')];if(nav[0]){nav[0].dataset.view='program';nav[0].innerHTML='<b>🗓️</b>Programa'}if(nav[1]){nav[1].dataset.view='favorites';nav[1].innerHTML='<b>♥</b>Mi plan'}if(nav[2]){nav[2].dataset.view='itinerary';nav[2].innerHTML='<b>⚙️</b>Admin';nav[2].style.display=ownerSecret?'block':'none'}const inner=document.querySelector('.navinner');if(inner)inner.style.gridTemplateColumns=ownerSecret?'repeat(3,1fr)':'repeat(2,1fr)';nav.forEach(b=>{const clone=b.cloneNode(true);b.replaceWith(clone);clone.addEventListener('click',()=>{state.view=clone.dataset.view;save();render();if(state.view==='itinerary')refreshAdmin()})})}
const oldRender=render;render=function(){document.getElementById('programFilters').style.display=state.view==='program'?'block':'none';document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));if(state.view==='program')renderProgram();else if(state.view==='favorites')renderFavorites();else renderItinerary()}

async function boot(){configureNav();setupFilters();render();try{await ensureRuntime();if(roomId&&inviteKey){await refreshRoom(false);if(ownerSecret)await refreshAdmin();pollTimer=setInterval(async()=>{if(document.visibilityState!=='visible')return;await refreshRoom(true);if(state.view==='itinerary'&&ownerSecret)await refreshAdmin()},7000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){refreshRoom(false);if(state.view==='itinerary'&&ownerSecret)refreshAdmin()}})}}catch(e){console.error(e);document.getElementById('app').innerHTML='<div class="empty">No se pudo iniciar la aplicación.</div>'}}
window.addEventListener('beforeunload',()=>{if(pollTimer)clearInterval(pollTimer)});
boot();
})();