(() => {
'use strict';
if (window.__FROMAGO_V9__) return;
window.__FROMAGO_V9__ = true;
const APP_VERSION='9.0.0';
const params=new URL(location.href).searchParams;
const roomId=params.get('room');
let inviteKey=params.get('k');
let roomData=null,roomSig='',client=null,pollTimer=null,loading=false;
let meId=null,mySecret=null,ownerSecret=null,viewPerson='group';
const DEVICE_KEY='fromago-secure-device-v1';
const CAT_KEY='fromago-v9-categories';
const ALL_GROUPS=GROUPS.filter(g=>g!=='Todo');
const key=(s)=>roomId?`fromago-secure-${s}:${roomId}`:`fromago-secure-${s}`;
function rnd(){const a=new Uint8Array(32);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
function deviceSecret(){let x=localStorage.getItem(DEVICE_KEY);if(!x){x=rnd();localStorage.setItem(DEVICE_KEY,x)}return x}
function loadCreds(){if(!roomId)return;meId=localStorage.getItem(key('participant-id'));mySecret=localStorage.getItem(key('participant-secret'));ownerSecret=localStorage.getItem(key('owner-secret'));viewPerson=localStorage.getItem(key('view'))||'group'}
loadCreds();
let enabledGroups;
try{const saved=JSON.parse(localStorage.getItem(CAT_KEY)||'null');enabledGroups=new Set(Array.isArray(saved)?saved.filter(g=>ALL_GROUPS.includes(g)):ALL_GROUPS.filter(g=>g!=='Profesional'))}catch(e){enabledGroups=new Set(ALL_GROUPS.filter(g=>g!=='Profesional'))}
if(!enabledGroups.size) enabledGroups=new Set(ALL_GROUPS.filter(g=>g!=='Profesional'));
function saveCats(){localStorage.setItem(CAT_KEY,JSON.stringify([...enabledGroups]))}

const css=document.createElement('style');
css.textContent=`
body{--grid-red:#fff0ee;--grid-green:#eaf7f1;--grid-amber:#fff7d6}
.securebar{margin:8px 0;padding:7px 9px;border:1px solid var(--line);border-left:3px solid var(--green);border-radius:10px;background:var(--greenbg);font-size:11px;line-height:1.35}.securebar.warn{border-left-color:var(--warn);background:var(--warnbg)}
.people{background:#fff;border:1px solid var(--line);border-radius:13px;padding:9px;margin:8px 0}.peoplehead{display:flex;justify-content:space-between;align-items:center;gap:8px}.peoplehead h2{font-size:13px;margin:0}.prow{display:flex;align-items:center;gap:7px;border-top:1px solid var(--line);padding:6px 0}.prow:first-child{border-top:0}.pname{font-weight:800;flex:1;font-size:12px}.pcount{font-size:10px;color:var(--muted)}.tiny{border:1px solid var(--line);background:#fff;border-radius:8px;padding:5px 7px;font-size:10px;font-weight:800}.tiny.danger{color:var(--danger)}.meonly{font-size:9px;color:var(--green);font-weight:900}.readonly{font-size:10px;color:var(--muted)}
.adminbox{background:#fff;border:1px solid var(--line);border-radius:12px;padding:8px;margin:8px 0}.adminbox h3{font-size:11px;margin:0 0 6px}.adminrow{display:flex;gap:6px;flex-wrap:wrap}
.viewtabs{display:flex;gap:6px;overflow:auto;padding:3px 0 8px}.viewtab{white-space:nowrap;border:1px solid var(--line);background:#fff;border-radius:999px;padding:6px 9px;font-size:11px;font-weight:800}.viewtab.active{background:var(--ink);color:#fff;border-color:var(--ink)}
.joinback{position:fixed;inset:0;background:rgba(10,10,10,.68);z-index:9999;display:flex;align-items:center;justify-content:center;padding:18px}.joincard{width:min(440px,100%);background:#fffaf0;border-radius:20px;padding:20px;box-shadow:0 24px 80px rgba(0,0,0,.3)}.joincard h2{margin:7px 0 6px}.joincard p{font-size:12px;line-height:1.5;color:var(--muted)}.joinrow{display:flex;gap:8px;margin-top:13px}.joinrow input{min-width:0;flex:1;border:1px solid var(--line);border-radius:11px;padding:11px 12px;font:inherit}.joinrow button{border:0;background:var(--cheese);border-radius:11px;padding:10px 13px;font-weight:850}
.card{padding:10px 11px;margin:6px 0;border-radius:14px}.title{font-size:14px;margin:6px 0 5px}.meta{font-size:11px}.details{font-size:11px;margin-top:5px}.actions{margin-top:7px;align-items:center}.badge{font-size:9px;padding:4px 6px}.time{font-size:12px}
.heartbtn{width:34px;height:34px;border-radius:50%;border:1px solid var(--line);background:#fff;font-size:20px;line-height:1;display:grid;place-items:center;padding:0;flex:0 0 34px}.heartbtn.on{background:var(--ink);color:#fff;border-color:var(--ink)}.heartbtn:active{transform:scale(.95)}
.matchbadge{display:inline-flex;align-items:center;gap:3px;background:var(--greenbg);color:var(--green);border:1px solid #b9e3d3;border-radius:999px;padding:4px 7px;font-size:10px;font-weight:850}.interestnames{font-size:10px;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:220px}
.summarystrip{display:flex;gap:7px;overflow:auto;margin:8px 0}.summarypill{white-space:nowrap;background:#fff;border:1px solid var(--line);border-radius:999px;padding:6px 9px;font-size:10px;font-weight:800}.summarypill.good{background:var(--greenbg);color:var(--green);border-color:#b9e3d3}.summarypill.bad{background:var(--dangerbg);color:var(--danger);border-color:#f2c6c1}
.timelinewrap{overflow:auto;border:1px solid var(--line);border-radius:13px;background:#fff;margin:8px 0 16px;max-height:68vh}.timeline{border-collapse:separate;border-spacing:0;min-width:max-content;width:100%;font-size:10px}.timeline th,.timeline td{border-right:1px solid var(--line);border-bottom:1px solid var(--line);vertical-align:top}.timeline th:last-child,.timeline td:last-child{border-right:0}.timeline tr:last-child td{border-bottom:0}.timeline thead th{position:sticky;top:0;z-index:4;background:#fffaf0;padding:7px 8px;min-width:145px;text-align:left}.timeline .timecol{position:sticky;left:0;z-index:5;min-width:64px;width:64px;background:#fffaf0;font-weight:900;padding:7px 6px;text-align:center}.timeline thead .timecol{z-index:6}.timeline .mehead{background:var(--soft)}.tcell{padding:5px;min-width:145px;max-width:180px;background:#fff;position:relative}.tcell.overlap{background:var(--grid-red);box-shadow:inset 0 0 0 2px #e8877e}.tcell.near{background:var(--grid-amber)}.tcell.me{background-image:linear-gradient(rgba(242,201,76,.09),rgba(242,201,76,.09))}.tcell.overlap.me{background:var(--grid-red)}.titem{padding:4px 5px;border-radius:7px;background:#f7f3eb;margin-bottom:4px;line-height:1.25}.titem:last-child{margin-bottom:0}.titem.shared{background:var(--grid-green);border:1px solid #b9e3d3}.titem.cont{opacity:.72;border-style:dashed}.ttitle{font-weight:800;display:block;max-width:160px}.tmeta{display:flex;gap:4px;align-items:center;margin-top:2px;color:var(--muted);font-size:9px}.overlapnum{position:absolute;right:4px;top:4px;min-width:20px;height:20px;padding:0 5px;border-radius:999px;background:var(--danger);color:#fff;display:grid;place-items:center;font-size:10px;font-weight:900}.gridlegend{font-size:10px;color:var(--muted);line-height:1.45;margin:6px 2px 10px}.daygridtitle{display:flex;justify-content:space-between;align-items:center;margin:14px 2px 5px}.daygridtitle h2{font-size:15px;margin:0}.daygridtitle span{font-size:10px;color:var(--muted)}
@media(max-width:480px){.timeline thead th,.tcell{min-width:132px}.timeline .timecol{min-width:58px;width:58px}.interestnames{max-width:145px}}
`;
document.head.appendChild(css);
document.title='FROMAGO · Plan compartido';
const h1=document.querySelector('.hero h1');if(h1)h1.textContent='FROMAGO · Plan compartido';

function participant(id){return roomData?.participants?.find(p=>p.id===id)}
function myParticipant(){return participant(meId)}
function selectionsOf(id){return participant(id)?.selections||[]}
function allSelected(){const s=new Set();for(const p of roomData?.participants||[])for(const id of p.selections||[])s.add(id);return ACTIVITIES.filter(a=>s.has(a.id))}
function namesFor(actId){return (roomData?.participants||[]).filter(p=>(p.selections||[]).includes(actId)).map(p=>p.name)}
function activeActivities(){if(viewPerson==='group'||!participant(viewPerson))return allSelected().sort(sortActs);const ids=new Set(selectionsOf(viewPerson));return ACTIVITIES.filter(a=>ids.has(a.id)).sort(sortActs)}
function viewLabel(){return viewPerson==='group'?'Todo el grupo':participant(viewPerson)?.name||'Todo el grupo'}
function errCode(e){return String(e?.message||e||'').match(/(name_taken|device_already_joined|device_banned|room_locked|room_full|join_rate_limited|room_not_found|invalid_name_length|invalid_name_chars|owner_only|not_your_participant)/)?.[1]||''}
function explain(e){const c=errCode(e);return ({name_taken:'Ese nombre ya está utilizado en este grupo.',device_already_joined:'Este dispositivo ya tiene un participante en el grupo.',device_banned:'Este dispositivo fue bloqueado por el propietario.',room_locked:'El propietario ha cerrado nuevas incorporaciones.',room_full:'El grupo ha alcanzado el límite de participantes.',join_rate_limited:'Se han producido demasiadas altas en poco tiempo. Prueba más tarde.',room_not_found:'El enlace ya no es válido.',invalid_name_length:'El nombre debe tener entre 2 y 32 caracteres.',invalid_name_chars:'Usa solo letras, números, espacios, punto, guion o apóstrofo.',owner_only:'Acción reservada al propietario.',not_your_participant:'No puedes modificar el itinerario de otra persona.'}[c]||'No se pudo completar la operación.')}
function loadScript(src){return new Promise((ok,bad)=>{const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=bad;document.head.appendChild(s)})}
async function ensureRuntime(){if(client)return client;await loadScript('./sync-config.js?v=9');if(!window.supabase?.createClient)await loadScript('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/dist/umd/supabase.min.js');const c=window.FROMAGO_SYNC;if(!c?.supabaseUrl||!c?.supabaseKey)throw new Error('sync_config');client=window.supabase.createClient(c.supabaseUrl,c.supabaseKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});return client}

window.createSecureGroup=async function(){let name=prompt('Tu nombre como creador del grupo');if(name==null)return;name=name.trim();if(!name)return;try{const c=await ensureRuntime();const os=rnd(),ik=rnd(),ps=rnd(),ds=deviceSecret();const {data,error}=await c.rpc('fromago_secure_create_room',{p_owner_secret:os,p_invite_secret:ik,p_device_secret:ds,p_participant_secret:ps,p_name:name});if(error)throw error;const rid=data.room_id,pid=data.participant_id;localStorage.setItem(`fromago-secure-owner-secret:${rid}`,os);localStorage.setItem(`fromago-secure-participant-id:${rid}`,pid);localStorage.setItem(`fromago-secure-participant-secret:${rid}`,ps);const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('room',rid);u.searchParams.set('k',ik);u.searchParams.set('appv','9');location.href=u.toString()}catch(e){console.error(e);toast(explain(e))}}
window.joinSecureGroup=async function(){const inp=document.getElementById('secureName');let name=(inp?.value||'').trim();if(!name)return;try{const c=await ensureRuntime(),ps=rnd();const {data,error}=await c.rpc('fromago_secure_join_room',{p_room_id:roomId,p_invite_secret:inviteKey,p_device_secret:deviceSecret(),p_participant_secret:ps,p_name:name});if(error)throw error;meId=String(data);mySecret=ps;localStorage.setItem(key('participant-id'),meId);localStorage.setItem(key('participant-secret'),mySecret);document.getElementById('joinOverlay')?.remove();await refreshRoom(false);viewPerson=meId;localStorage.setItem(key('view'),viewPerson);render()}catch(e){console.error(e);toast(explain(e))}}
function showJoin(){if(!roomId||myParticipant()||document.getElementById('joinOverlay')||roomData?.locked)return;const el=document.createElement('div');el.id='joinOverlay';el.className='joinback';el.innerHTML=`<div class="joincard"><span class="badge">INVITACIÓN AL GRUPO</span><h2>Elige tu nombre</h2><p>El nombre quedará fijado. Este dispositivo solo puede crear un participante en el grupo. Después podrás modificar únicamente tu propio itinerario y consultar el de los demás.</p><div class="joinrow"><input id="secureName" maxlength="32" autocomplete="name" placeholder="Tu nombre"><button onclick="joinSecureGroup()">Entrar</button></div><p class="readonly">Los nombres no pueden repetirse.</p></div>`;document.body.appendChild(el);document.getElementById('secureName')?.addEventListener('keydown',e=>{if(e.key==='Enter')joinSecureGroup()});setTimeout(()=>document.getElementById('secureName')?.focus(),50)}
window.showSecureJoin=showJoin;

async function refreshRoom(silent=false){if(!roomId||!inviteKey||loading)return false;loading=true;let changed=false;try{const c=await ensureRuntime();const {data,error}=await c.rpc('fromago_secure_get_room',{p_room_id:roomId,p_invite_secret:inviteKey});if(error)throw error;const sig=JSON.stringify(data);changed=sig!==roomSig;roomSig=sig;roomData=data;if(meId&&!participant(meId)){meId=null;mySecret=null;localStorage.removeItem(key('participant-id'));localStorage.removeItem(key('participant-secret'))}if(viewPerson!=='group'&&!participant(viewPerson))viewPerson=meId&&participant(meId)?meId:'group';if(!silent||changed)render();if(!myParticipant())showJoin();return changed}catch(e){console.error(e);if(!silent)document.getElementById('app').innerHTML=`<div class="empty">${esc(explain(e))}</div>`;return false}finally{loading=false}}
async function saveMine(){if(!myParticipant()||!mySecret)return;const c=await ensureRuntime();const {error}=await c.rpc('fromago_secure_save_itinerary',{p_room_id:roomId,p_invite_secret:inviteKey,p_participant_id:meId,p_participant_secret:mySecret,p_activity_ids:selectionsOf(meId)});if(error)throw error}
window.toggleSecureFav=async function(actId){if(!myParticipant()){showJoin();return}const p=myParticipant();p.selections=p.selections||[];const i=p.selections.indexOf(actId);i>=0?p.selections.splice(i,1):p.selections.push(actId);render();try{await saveMine();await refreshRoom(true)}catch(e){toast(explain(e));await refreshRoom(false)}}
window.setSecureView=function(id){viewPerson=(id==='group'||participant(id))?id:'group';localStorage.setItem(key('view'),viewPerson);render()}

window.toggleCategory=function(g){if(g==='__all__'){enabledGroups=new Set(ALL_GROUPS)}else if(enabledGroups.has(g)){enabledGroups.delete(g)}else enabledGroups.add(g);saveCats();setupFilters();renderProgram()}
setupFilters=function(){
 document.getElementById('daychips').innerHTML=['Todos',...DAY_ORDER].map(d=>`<button class="chip ${state.day===d?'active':''}" onclick="state.day='${d}';save();setupFilters();render()">${d==='Todos'?'Todos':fmtDay(d)}</button>`).join('');
 const allOn=ALL_GROUPS.every(g=>enabledGroups.has(g));
 document.getElementById('catchips').innerHTML=`<button class="chip ${allOn?'active':''}" onclick="toggleCategory('__all__')">Todas</button>`+ALL_GROUPS.map(g=>`<button class="chip ${enabledGroups.has(g)?'active':''}" onclick="toggleCategory('${esc(g)}')">${esc(g)}</button>`).join('');
 const locs=[...new Set(ACTIVITIES.map(a=>a.location))].sort((x,y)=>x.localeCompare(y,'es'));
 const sel=document.getElementById('locfilter');sel.innerHTML='<option value="">Todos los espacios</option>'+locs.map(l=>`<option ${state.loc===l?'selected':''}>${esc(l)}</option>`).join('');
 document.getElementById('search').value=state.query||'';document.getElementById('regOnly').checked=!!state.regOnly;
}
filtered=function(){let q=(state.query||'').toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu,'');return ACTIVITIES.filter(a=>{let hay=[a.title,a.location,a.details,a.category,a.group].join(' ').toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu,'');return (state.day==='Todos'||a.day===state.day)&&enabledGroups.has(a.group)&&(!q||hay.includes(q))&&(!state.regOnly||a.registration)&&(!state.loc||a.location===state.loc)})}

function favArea(a){if(!roomId)return `<button class="heartbtn" onclick="createSecureGroup()" aria-label="Crear grupo" title="Crear grupo">♡</button>`;if(!myParticipant())return `<button class="heartbtn" onclick="showSecureJoin()" aria-label="Unirme para elegir" title="Unirme para elegir">♡</button>`;const on=selectionsOf(meId).includes(a.id);const names=namesFor(a.id),others=names.filter(n=>n!==myParticipant()?.name);return `<button class="heartbtn ${on?'on':''}" onclick="toggleSecureFav(${a.id})" aria-label="${on?'Quitar de mi itinerario':'Añadir a mi itinerario'}" title="${on?'Quitar':'Me interesa'}">${on?'♥':'♡'}</button>${names.length>=2?`<span class="matchbadge">👥 ${names.length}</span>`:''}${others.length?`<span class="interestnames">${others.map(esc).join(', ')}</span>`:''}`}
card=function(a,extra=''){return `<article class="card ${a.time==='Todo el día'?'allDay':''}"><div class="topline"><span class="badge">${esc(a.category)}</span><span class="time">${esc(a.time)}${a.end?'–'+esc(a.end):''}</span></div><div class="title">${esc(a.title)}</div><div class="meta"><strong>📍 ${esc(a.location)}</strong>${a.registration?' · ✍️ Inscripción':''}${a.paid?' · 💳 De pago':''}</div>${a.details?`<div class="details">${esc(a.details)}</div>`:''}${extra}<div class="actions">${favArea(a)}</div></article>`}

function secureNotice(){if(!roomId)return `<div class="securebar warn"><b>Modo seguro.</b> Crea un grupo y comparte el enlace.</div>`;return `<div class="securebar"><b>● Grupo seguro.</b> ${myParticipant()?`Tú: <b>${esc(myParticipant().name)}</b>.`:'Consulta el grupo o únete para crear tu itinerario.'}</div>`}
function tabs(){if(!roomData)return'';return `<div class="viewtabs"><button class="viewtab ${viewPerson==='group'?'active':''}" onclick="setSecureView('group')">Todo el grupo</button>${myParticipant()?`<button class="viewtab ${viewPerson===meId?'active':''}" onclick="setSecureView('${esc(meId)}')">Mi plan</button>`:''}${roomData.participants.filter(p=>p.id!==meId).map(p=>`<button class="viewtab ${viewPerson===p.id?'active':''}" onclick="setSecureView('${esc(p.id)}')">${esc(p.name)}</button>`).join('')}</div>`}
function participantsBox(){if(!roomData)return'';return `<div class="people"><div class="peoplehead"><h2>Participantes · ${roomData.participants.length}/${roomData.max_participants}</h2><span class="readonly">${roomData.locked?'🔒 Cerrado':'Abierto'}</span></div>${roomData.participants.map(p=>`<div class="prow"><span class="pname">${esc(p.name)} ${p.id===meId?'<span class="meonly">TÚ</span>':''}</span><span class="pcount">${(p.selections||[]).length}</span>${ownerSecret&&p.id!==meId?`<button class="tiny danger" onclick="ownerKick('${esc(p.id)}','${esc(p.name)}')">Expulsar</button>`:''}</div>`).join('')}</div>`}
function adminBox(){if(!ownerSecret||!roomData)return'';return `<div class="adminbox"><h3>Administración · solo propietario</h3><div class="adminrow"><button class="tiny" onclick="ownerToggleLock()">${roomData.locked?'Abrir altas':'Cerrar altas'}</button><button class="tiny" onclick="ownerRotateLink()">Regenerar enlace</button></div></div>`}

renderProgram=function(){const arr=filtered(),app=document.getElementById('app');document.getElementById('countpill').textContent=`${arr.length} de 221`;let out=secureNotice();if(!arr.length){app.innerHTML=out+'<div class="empty">No hay actividades con estos filtros.</div>';return}for(const day of DAY_ORDER){const items=arr.filter(a=>a.day===day);if(!items.length)continue;out+=`<div class="sectiontitle"><h2>${day}</h2><span>${items.length}</span></div><div class="cardsgrid">`;let last=null;for(const a of items){if(a.time!==last){out+=`<div class="slot">${a.time}</div>`;last=a.time}out+=card(a)}out+='</div>'}app.innerHTML=out}
renderFavorites=function(){if(!roomId){document.getElementById('countpill').textContent='Grupo seguro';document.getElementById('app').innerHTML=secureNotice()+`<div class="sharebox"><button class="primary" onclick="createSecureGroup()">🔒 Crear grupo compartido</button></div><div class="empty">El grupo empieza vacío. Tú serás el propietario.</div>`;return}if(!roomData){document.getElementById('app').innerHTML='<div class="empty">Cargando grupo…</div>';return}const arr=activeActivities();document.getElementById('countpill').textContent=`${arr.length} · ${viewLabel()}`;const shared=allSelected().filter(a=>namesFor(a.id).length>=2).length;let out=secureNotice()+`<div class="summarystrip"><span class="summarypill good">👥 ${shared} coincidencias</span><span class="summarypill">${roomData.participants.length} participantes</span></div>`+participantsBox()+adminBox()+tabs()+`<div class="sharebox"><button class="primary" onclick="shareSecureLink()">Compartir enlace</button><button class="secondary" onclick="shareText()">Compartir itinerario</button></div>`;if(!arr.length)out+=`<div class="empty">${viewPerson==='group'?'Todavía no hay intereses en el grupo.':`${esc(viewLabel())} todavía no ha elegido actividades.`}</div>`;for(const day of DAY_ORDER){const items=arr.filter(a=>a.day===day);if(!items.length)continue;out+=`<div class="sectiontitle"><h2>${day}</h2><span>${items.length}</span></div>`;for(const a of items){const names=namesFor(a.id);out+=card(a,names.length?`<div class="details">${names.length>=2?`<span class="matchbadge">👥 ${names.length}</span> `:''}${names.map(esc).join(', ')}</div>`:'')}}document.getElementById('app').innerHTML=out}

function startsFor(pid,day,time){return ACTIVITIES.filter(a=>a.day===day&&a.time===time&&selectionsOf(pid).includes(a.id))}
function activeAt(pid,day,time){if(time==='Todo el día')return startsFor(pid,day,time).map(a=>({a,cont:false}));const t=mins(time);if(t==null)return[];const out=[];for(const a of ACTIVITIES){if(a.day!==day||!selectionsOf(pid).includes(a.id)||a.time==='Todo el día')continue;const s=mins(a.time);if(s==null)continue;if(s===t)out.push({a,cont:false});else if(a.end){const e=mins(a.end);if(e!=null&&s<t&&t<e)out.push({a,cont:true})}}return out}
function nearAt(pid,day,time){const t=mins(time);if(t==null)return false;const starts=startsFor(pid,day,time);if(!starts.length)return false;const selected=ACTIVITIES.filter(a=>a.day===day&&selectionsOf(pid).includes(a.id)&&a.time!=='Todo el día');return selected.some(a=>{const x=mins(a.time);return x!=null&&x!==t&&Math.abs(x-t)<state.buffer})}
function gridStats(){let overlaps=0;const shared=allSelected().filter(a=>namesFor(a.id).length>=2).length;for(const p of roomData?.participants||[])for(const day of DAY_ORDER){const times=[...new Set(ACTIVITIES.filter(a=>a.day===day&&selectionsOf(p.id).includes(a.id)&&a.time!=='Todo el día').map(a=>a.time))];for(const t of times)if(activeAt(p.id,day,t).length>=2)overlaps++}return{overlaps,shared}}
function cellHtml(pid,day,time){const active=activeAt(pid,day,time);const starts=active.filter(x=>!x.cont);const overlap=active.length>=2;const near=!overlap&&nearAt(pid,day,time);const cls=['tcell',pid===meId?'me':'',overlap?'overlap':'',near?'near':''].filter(Boolean).join(' ');let html=`<td class="${cls}">`;if(overlap)html+=`<span class="overlapnum">${active.length}</span>`;for(const {a,cont} of active){const n=namesFor(a.id).length;html+=`<div class="titem ${n>=2?'shared':''} ${cont?'cont':''}"><span class="ttitle">${cont?'↳ ':''}${esc(a.title)}</span><span class="tmeta">${cont?'continúa':esc(a.category)}${n>=2?` · 👥${n}`:''}</span></div>`}if(!active.length&&starts.length===0)html+='&nbsp;';return html+'</td>'}
function gridForDay(day){const selected=allSelected().filter(a=>a.day===day);if(!selected.length)return'';let times=[...new Set(selected.map(a=>a.time))];times.sort((a,b)=>{if(a==='Todo el día')return 1;if(b==='Todo el día')return-1;return(mins(a)||9999)-(mins(b)||9999)});const ps=roomData.participants;let out=`<div class="daygridtitle"><h2>${day}</h2><span>desliza horizontalmente</span></div><div class="timelinewrap"><table class="timeline"><thead><tr><th class="timecol">Hora</th>${ps.map(p=>`<th class="${p.id===meId?'mehead':''}">${esc(p.name)}${p.id===meId?' · Tú':''}</th>`).join('')}</tr></thead><tbody>`;for(const time of times){out+=`<tr><td class="timecol">${esc(time)}</td>${ps.map(p=>cellHtml(p.id,day,time)).join('')}</tr>`}return out+'</tbody></table></div>'}
renderItinerary=function(){if(!roomId){renderFavorites();return}if(!roomData){document.getElementById('app').innerHTML='<div class="empty">Cargando grupo…</div>';return}const stats=gridStats();document.getElementById('countpill').textContent=`${stats.shared} coincidencias`;let out=secureNotice()+`<div class="summarystrip"><span class="summarypill good">👥 ${stats.shared} actividades compartidas</span><span class="summarypill bad">⛔ ${stats.overlaps} solapes</span></div><div class="settings"><label>Margen de proximidad <select onchange="state.buffer=+this.value;save();render()">${[15,30,45,60,90].map(v=>`<option value="${v}" ${state.buffer===v?'selected':''}>${v} min</option>`).join('')}</select></label></div><div class="gridlegend"><b>Rojo + número:</b> actividades simultáneas o solape confirmado para esa persona. <b>Verde 👥:</b> la misma actividad interesa a varias personas. <b>Ámbar:</b> dos inicios quedan dentro del margen elegido.</div>`;if(!allSelected().length)out+='<div class="empty">Todavía no hay actividades en el grupo.</div>';else for(const day of DAY_ORDER)out+=gridForDay(day);document.getElementById('app').innerHTML=out}

selectedActivities=function(){return roomData?allSelected():[]};
personHas=function(pid,id){return selectionsOf(pid).includes(id)};chosenPeople=function(id){return namesFor(id)};personName=function(pid){return participant(pid)?.name||'Visitante'};
window.shareSecureLink=async function(){const u=new URL(location.href);u.searchParams.delete('appv');const data={title:'Plan FROMAGO',text:'Únete al plan compartido. Elige tu nombre y marca tu propio itinerario.',url:u.toString()};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);toast('Enlace copiado')}}catch(e){}}
window.ownerToggleLock=async function(){try{const c=await ensureRuntime();const {error}=await c.rpc('fromago_secure_owner_lock',{p_room_id:roomId,p_owner_secret:ownerSecret,p_locked:!roomData.locked});if(error)throw error;await refreshRoom(false)}catch(e){toast(explain(e))}}
window.ownerKick=async function(pid,name){if(!confirm(`¿Expulsar y bloquear a ${name} en este grupo?`))return;try{const c=await ensureRuntime();const {error}=await c.rpc('fromago_secure_owner_remove_participant',{p_room_id:roomId,p_owner_secret:ownerSecret,p_participant_id:pid});if(error)throw error;await refreshRoom(false)}catch(e){toast(explain(e))}}
window.ownerRotateLink=async function(){if(!confirm('Se invalidará el enlace actual. ¿Continuar?'))return;try{const nk=rnd(),c=await ensureRuntime();const {error}=await c.rpc('fromago_secure_owner_rotate_invite',{p_room_id:roomId,p_owner_secret:ownerSecret,p_new_invite_secret:nk});if(error)throw error;const u=new URL(location.href);u.searchParams.set('k',nk);u.searchParams.set('appv','9');history.replaceState(null,'',u);inviteKey=nk;await refreshRoom(false)}catch(e){toast(explain(e))}}
itineraryText=function(){const arr=activeActivities();let lines=[`🧀 FROMAGO 2026 · ${viewLabel()}`],d='';for(const a of arr){if(a.day!==d){d=a.day;lines.push('',`— ${d} —`)}lines.push(`${a.time} · ${a.title} · ${a.location} · ${namesFor(a.id).join(', ')}`)}return lines.join('\n')}

async function boot(){try{setupFilters();render();await ensureRuntime();if(roomId&&inviteKey){await refreshRoom(false);pollTimer=setInterval(()=>{if(document.visibilityState==='visible')refreshRoom(true)},5000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refreshRoom(true)})}else render()}catch(e){console.error(e);document.getElementById('app').innerHTML='<div class="empty">No se pudo iniciar la aplicación.</div>'}}
window.addEventListener('beforeunload',()=>{if(pollTimer)clearInterval(pollTimer)});
boot();
})();
