(() => {
'use strict';
const APP_VERSION='8.0.0';
const params=new URL(location.href).searchParams;
const roomId=params.get('room');
const inviteKey=params.get('k');
let roomData=null, client=null, pollTimer=null, loading=false;
let meId=null, mySecret=null, ownerSecret=null;
let viewPerson='group';
const DEVICE_KEY='fromago-secure-device-v1';
const key=(s)=>roomId?`fromago-secure-${s}:${roomId}`:`fromago-secure-${s}`;
function rnd(){const a=new Uint8Array(32);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
function deviceSecret(){let x=localStorage.getItem(DEVICE_KEY);if(!x){x=rnd();localStorage.setItem(DEVICE_KEY,x)}return x}
function loadCreds(){if(!roomId)return;meId=localStorage.getItem(key('participant-id'));mySecret=localStorage.getItem(key('participant-secret'));ownerSecret=localStorage.getItem(key('owner-secret'));viewPerson=localStorage.getItem(key('view'))||'group'}
loadCreds();

const css=document.createElement('style');
css.textContent=`
.securebar{margin:12px 0;padding:11px 12px;border:1px solid var(--line);border-left:4px solid var(--green);border-radius:12px;background:var(--greenbg);font-size:12px;line-height:1.45}.securebar.warn{border-left-color:var(--warn);background:var(--warnbg)}
.people{background:#fff;border:1px solid var(--line);border-radius:15px;padding:12px;margin:12px 0}.peoplehead{display:flex;justify-content:space-between;align-items:center;gap:8px}.peoplehead h2{font-size:15px;margin:0}.prow{display:flex;align-items:center;gap:8px;border-top:1px solid var(--line);padding:9px 0}.prow:first-child{border-top:0}.pname{font-weight:850;flex:1}.pcount{font-size:11px;color:var(--muted)}.ownerbadge{font-size:9px;font-weight:900;background:var(--soft);border:1px solid #efd46b;border-radius:999px;padding:3px 6px}.tiny{border:1px solid var(--line);background:#fff;border-radius:9px;padding:7px 8px;font-size:11px;font-weight:800}.tiny.danger{color:var(--danger)}
.viewtabs{display:flex;gap:7px;overflow:auto;padding:4px 0 11px}.viewtab{white-space:nowrap;border:1px solid var(--line);background:#fff;border-radius:999px;padding:8px 11px;font-weight:800}.viewtab.active{background:var(--ink);color:#fff;border-color:var(--ink)}
.joinback{position:fixed;inset:0;background:rgba(10,10,10,.68);z-index:9999;display:flex;align-items:center;justify-content:center;padding:18px}.joincard{width:min(440px,100%);background:#fffaf0;border-radius:20px;padding:20px;box-shadow:0 24px 80px rgba(0,0,0,.3)}.joincard h2{margin:7px 0 6px}.joincard p{font-size:12px;line-height:1.5;color:var(--muted)}.joinrow{display:flex;gap:8px;margin-top:13px}.joinrow input{min-width:0;flex:1;border:1px solid var(--line);border-radius:11px;padding:11px 12px;font:inherit}.joinrow button{border:0;background:var(--cheese);border-radius:11px;padding:10px 13px;font-weight:850}.adminbox{background:#fff;border:1px solid var(--line);border-radius:14px;padding:11px;margin:12px 0}.adminbox h3{font-size:13px;margin:0 0 8px}.adminrow{display:flex;gap:7px;flex-wrap:wrap}.meonly{font-size:11px;color:var(--green);font-weight:850}.readonly{font-size:11px;color:var(--muted)}
`;
document.head.appendChild(css);
document.title='FROMAGO · Plan compartido seguro';
const h1=document.querySelector('.hero h1');if(h1)h1.textContent='FROMAGO · Plan compartido';

function participant(id){return roomData?.participants?.find(p=>p.id===id)}
function myParticipant(){return participant(meId)}
function selectionsOf(id){return participant(id)?.selections||[]}
function allSelected(){const s=new Set();for(const p of roomData?.participants||[])for(const id of p.selections||[])s.add(id);return ACTIVITIES.filter(a=>s.has(a.id))}
function namesFor(actId){return (roomData?.participants||[]).filter(p=>(p.selections||[]).includes(actId)).map(p=>p.name)}
function activeActivities(){if(viewPerson==='group'||!participant(viewPerson))return allSelected().sort(sortActs);const ids=new Set(selectionsOf(viewPerson));return ACTIVITIES.filter(a=>ids.has(a.id)).sort(sortActs)}
function viewLabel(){return viewPerson==='group'?'Todo el grupo':participant(viewPerson)?.name||'Todo el grupo'}
function errCode(e){return String(e?.message||e||'').match(/(name_taken|device_already_joined|device_banned|room_locked|room_full|join_rate_limited|room_not_found|invalid_name_length|invalid_name_chars|owner_only|not_your_participant)/)?.[1]||''}
function explain(e){const c=errCode(e);return ({name_taken:'Ese nombre ya está utilizado en este grupo.',device_already_joined:'Este dispositivo ya tiene un participante en el grupo.',device_banned:'Este dispositivo fue bloqueado por el propietario.',room_locked:'El propietario ha cerrado nuevas incorporaciones.',room_full:'El grupo ha alcanzado el límite de participantes.',join_rate_limited:'Se han producido demasiadas altas en poco tiempo. Prueba más tarde.',room_not_found:'El enlace ya no es válido.',invalid_name_length:'El nombre debe tener entre 2 y 32 caracteres.',invalid_name_chars:'Usa solo letras, números, espacios, punto, guion o apóstrofo.',owner_only:'Acción reservada al propietario.',not_your_participant:'No puedes modificar el itinerario de otra persona.'}[c]||'No se pudo completar la operación.')}
async function ensureRuntime(){if(client)return client;await loadScript('./sync-config.js?v=8');await loadScript('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/dist/umd/supabase.min.js');const c=window.FROMAGO_SYNC;if(!c?.supabaseUrl||!c?.supabaseKey)throw new Error('sync_config');client=window.supabase.createClient(c.supabaseUrl,c.supabaseKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});return client}
function loadScript(src){return new Promise((ok,bad)=>{const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=bad;document.head.appendChild(s)})}

window.createSecureGroup=async function(){let name=prompt('Tu nombre como creador del grupo');if(name==null)return;name=name.trim();if(!name)return;try{const c=await ensureRuntime();const os=rnd(),ik=rnd(),ps=rnd(),ds=deviceSecret();const {data,error}=await c.rpc('fromago_secure_create_room',{p_owner_secret:os,p_invite_secret:ik,p_device_secret:ds,p_participant_secret:ps,p_name:name});if(error)throw error;const rid=data.room_id,pid=data.participant_id;localStorage.setItem(`fromago-secure-owner-secret:${rid}`,os);localStorage.setItem(`fromago-secure-participant-id:${rid}`,pid);localStorage.setItem(`fromago-secure-participant-secret:${rid}`,ps);const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('room',rid);u.searchParams.set('k',ik);u.searchParams.set('appv','8');location.href=u.toString()}catch(e){console.error(e);toast(explain(e))}}

window.joinSecureGroup=async function(){const inp=document.getElementById('secureName');let name=(inp?.value||'').trim();if(!name)return;try{const c=await ensureRuntime(),ps=rnd();const {data,error}=await c.rpc('fromago_secure_join_room',{p_room_id:roomId,p_invite_secret:inviteKey,p_device_secret:deviceSecret(),p_participant_secret:ps,p_name:name});if(error)throw error;meId=String(data);mySecret=ps;localStorage.setItem(key('participant-id'),meId);localStorage.setItem(key('participant-secret'),mySecret);document.getElementById('joinOverlay')?.remove();await refreshRoom();viewPerson=meId;localStorage.setItem(key('view'),viewPerson);render()}catch(e){console.error(e);toast(explain(e))}}
function showJoin(){if(!roomId||myParticipant()||document.getElementById('joinOverlay')||roomData?.locked)return;const el=document.createElement('div');el.id='joinOverlay';el.className='joinback';el.innerHTML=`<div class="joincard"><span class="badge">INVITACIÓN AL GRUPO</span><h2>Elige tu nombre</h2><p>El nombre quedará fijado y no podrá cambiarse. Este dispositivo solo puede crear un participante en este grupo. Después podrás marcar únicamente tu propio itinerario y consultar el de los demás.</p><div class="joinrow"><input id="secureName" maxlength="32" autocomplete="name" placeholder="Tu nombre"><button onclick="joinSecureGroup()">Entrar</button></div><p class="readonly">No uses el nombre de otra persona: los nombres no pueden repetirse.</p></div>`;document.body.appendChild(el);document.getElementById('secureName')?.addEventListener('keydown',e=>{if(e.key==='Enter')joinSecureGroup()});setTimeout(()=>document.getElementById('secureName')?.focus(),50)}

async function refreshRoom(silent=false){if(!roomId||!inviteKey||loading)return;loading=true;try{const c=await ensureRuntime();const {data,error}=await c.rpc('fromago_secure_get_room',{p_room_id:roomId,p_invite_secret:inviteKey});if(error)throw error;roomData=data;if(meId&&!participant(meId)){meId=null;mySecret=null;localStorage.removeItem(key('participant-id'));localStorage.removeItem(key('participant-secret'))}if(viewPerson!=='group'&&!participant(viewPerson))viewPerson=meId&&participant(meId)?meId:'group';if(!silent)render();if(!myParticipant())showJoin()}catch(e){console.error(e);if(!silent)document.getElementById('app').innerHTML=`<div class="empty">${esc(explain(e))}</div>`}finally{loading=false}}
async function saveMine(){if(!myParticipant()||!mySecret)return;const c=await ensureRuntime();const {error}=await c.rpc('fromago_secure_save_itinerary',{p_room_id:roomId,p_invite_secret:inviteKey,p_participant_id:meId,p_participant_secret:mySecret,p_activity_ids:selectionsOf(meId)});if(error)throw error}
window.toggleSecureFav=async function(actId){if(!myParticipant()){showJoin();return}const p=myParticipant();p.selections=p.selections||[];const i=p.selections.indexOf(actId);i>=0?p.selections.splice(i,1):p.selections.push(actId);render();try{await saveMine();await refreshRoom(true)}catch(e){toast(explain(e));await refreshRoom()}}
window.setSecureView=function(id){viewPerson=(id==='group'||participant(id))?id:'group';localStorage.setItem(key('view'),viewPerson);render()}

function favArea(a){if(!roomId)return `<button class="fav" onclick="createSecureGroup()">🔒 Crear grupo para elegir</button>`;if(!myParticipant())return `<button class="fav" onclick="showSecureJoin()">＋ Unirme para elegir</button>`;const on=selectionsOf(meId).includes(a.id);const others=namesFor(a.id).filter(n=>n!==myParticipant()?.name);return `<button class="fav ${on?'on':''}" onclick="toggleSecureFav(${a.id})">${on?'♥':'♡'} Me interesa</button>${others.length?`<span class="readonly">También: ${others.map(esc).join(', ')}</span>`:''}`}
window.showSecureJoin=showJoin;
card=function(a,extra=''){const lnk=firstLink(a);return `<article class="card ${a.time==='Todo el día'?'allDay':''}"><div class="topline"><span class="badge">${esc(a.category)}</span><span class="time">${esc(a.time)}${a.end?'–'+esc(a.end):''}</span></div><div class="title">${esc(a.title)}</div><div class="meta"><strong>📍 ${esc(a.location)}</strong>${a.registration?' · ✍️ Inscripción':''}${a.paid?' · 💳 De pago':''}</div>${a.details?`<div class="details">${esc(a.details)}</div>`:''}${extra}<div class="actions">${favArea(a)}${lnk?`<a class="linkbtn ${a.registration?'reg':''}" href="${esc(lnk.url)}" target="_blank" rel="noopener">${a.registration?'Inscripción ↗':'Enlace ↗'}</a>`:''}</div></article>`}

function tabs(){if(!roomData)return'';return `<div class="viewtabs"><button class="viewtab ${viewPerson==='group'?'active':''}" onclick="setSecureView('group')">Todo el grupo</button>${myParticipant()?`<button class="viewtab ${viewPerson===meId?'active':''}" onclick="setSecureView('${esc(meId)}')">Mi plan · ${esc(myParticipant().name)}</button>`:''}${roomData.participants.filter(p=>p.id!==meId).map(p=>`<button class="viewtab ${viewPerson===p.id?'active':''}" onclick="setSecureView('${esc(p.id)}')">${esc(p.name)}</button>`).join('')}</div>`}
function participantsBox(){if(!roomData)return'';return `<div class="people"><div class="peoplehead"><h2>Participantes · ${roomData.participants.length}/${roomData.max_participants}</h2><span class="readonly">${roomData.locked?'🔒 Altas cerradas':'Altas abiertas'}</span></div>${roomData.participants.map(p=>`<div class="prow"><span class="pname">${esc(p.name)} ${p.id===meId?'<span class="meonly">TÚ</span>':''}</span><span class="pcount">${(p.selections||[]).length} intereses</span>${ownerSecret&&p.id!==meId?`<button class="tiny danger" onclick="ownerKick('${esc(p.id)}','${esc(p.name)}')">Expulsar</button>`:''}</div>`).join('')}</div>`}
function adminBox(){if(!ownerSecret||!roomData)return'';return `<div class="adminbox"><h3>Administración del grupo · solo tú</h3><div class="adminrow"><button class="tiny" onclick="ownerToggleLock()">${roomData.locked?'Abrir nuevas incorporaciones':'Cerrar nuevas incorporaciones'}</button><button class="tiny" onclick="ownerRotateLink()">Regenerar enlace</button></div><div class="readonly" style="margin-top:8px">Regenerar el enlace invalida inmediatamente el anterior.</div></div>`}
function secureNotice(){if(!roomId)return `<div class="securebar warn"><b>Modo seguro.</b> Crea un grupo para obtener un enlace compartido. El creador conserva la administración y cada invitado solo puede modificar su propio itinerario.</div>`;return `<div class="securebar"><b>● Grupo seguro.</b> ${myParticipant()?`Has entrado como <b>${esc(myParticipant().name)}</b>. Solo puedes modificar tu itinerario.`:'Puedes consultar el grupo; para elegir actividades debes unirte con un nombre nuevo.'}</div>`}

renderFavorites=function(){if(!roomId){document.getElementById('countpill').textContent='Grupo seguro';document.getElementById('app').innerHTML=secureNotice()+`<div class="sharebox"><button class="primary" onclick="createSecureGroup()">🔒 Crear grupo compartido</button></div><div class="empty">El grupo empieza vacío. Tú serás el propietario y después compartirás un enlace para que cada persona se añada con su propio nombre.</div>`;return}if(!roomData){document.getElementById('app').innerHTML='<div class="empty">Cargando grupo…</div>';return}const arr=activeActivities();document.getElementById('countpill').textContent=`${arr.length} · ${viewLabel()}`;let out=secureNotice()+participantsBox()+adminBox()+tabs()+`<div class="sharebox"><button class="primary" onclick="shareSecureLink()">Compartir enlace</button><button class="secondary" onclick="shareText()">Compartir itinerario</button></div>`;if(!arr.length)out+=`<div class="empty">${viewPerson==='group'?'Todavía no hay intereses en el grupo.':`${esc(viewLabel())} todavía no ha elegido actividades.`}</div>`;for(const day of DAY_ORDER){const items=arr.filter(a=>a.day===day);if(!items.length)continue;out+=`<div class="sectiontitle"><h2>${day}</h2><span>${items.length}</span></div>`;for(const a of items)out+=card(a,`<div class="details">Interesa a <div class="who">${namesFor(a.id).map(n=>`<span>${esc(n)}</span>`).join('')}</div></div>`)}document.getElementById('app').innerHTML=out}

function conflictMapFor(ids){const map={};for(const pid of ids){for(const day of DAY_ORDER){const xs=ACTIVITIES.filter(a=>a.day===day&&selectionsOf(pid).includes(a.id)&&a.time!=='Todo el día').sort(sortActs);for(let i=0;i<xs.length;i++)for(let j=i+1;j<xs.length;j++){const x=xs[i],y=xs[j],sx=mins(x.time),sy=mins(y.time);if(sx==null||sy==null)continue;let hard=false,soft=false,reason='';const ex=x.end?mins(x.end):null;if(sx===sy){hard=true;reason=`empiezan a la misma hora (${x.time})`}else if(ex!=null&&sy<ex){hard=true;reason=`${x.title} figura hasta las ${x.end}`}else if(sy-sx<state.buffer){soft=true;reason=`solo hay ${sy-sx} min entre los inicios`}if(hard||soft)for(const a of[x,y]){map[a.id]=map[a.id]||[];map[a.id].push({pid,hard,reason,other:a.id===x.id?y.title:x.title})}}}}return map}
renderItinerary=function(){if(!roomId){renderFavorites();return}if(!roomData){document.getElementById('app').innerHTML='<div class="empty">Cargando grupo…</div>';return}const arr=activeActivities();const ids=viewPerson==='group'?roomData.participants.map(p=>p.id):[viewPerson];const cm=conflictMapFor(ids);document.getElementById('countpill').textContent=`${arr.length} · ${viewLabel()}`;let out=secureNotice()+tabs()+`<div class="settings"><label>Margen para avisos <select onchange="state.buffer=+this.value;save();render()">${[15,30,45,60,90].map(v=>`<option value="${v}" ${state.buffer===v?'selected':''}>${v} min</option>`).join('')}</select></label></div>`;if(!arr.length)out+=`<div class="empty">${esc(viewLabel())} no tiene actividades.</div>`;for(const day of DAY_ORDER){const items=arr.filter(a=>a.day===day);if(!items.length)continue;out+=`<div class="sectiontitle"><h2>${day}</h2><span>${items.length}</span></div>`;for(const a of items){let x=`<div class="who">${namesFor(a.id).map(n=>`<span>${esc(n)}</span>`).join('')}</div>`;for(const c of cm[a.id]||[])x+=`<div class="conflict ${c.hard?'hard':'soft'}">${c.hard?'⛔':'⏱️'} ${esc(participant(c.pid)?.name||'')}: ${esc(c.reason)} · también “${esc(c.other)}”</div>`;out+=card(a,x)}}document.getElementById('app').innerHTML=out}
selectedActivities=function(){return roomData?allSelected():[]};
personHas=function(pid,id){return selectionsOf(pid).includes(id)};chosenPeople=function(id){return namesFor(id)};personName=function(pid){return participant(pid)?.name||'Visitante'};

window.shareSecureLink=async function(){const u=new URL(location.href);u.searchParams.delete('appv');const data={title:'Plan FROMAGO',text:'Únete al plan compartido. Elige tu nombre y marca tu propio itinerario.',url:u.toString()};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);toast('Enlace copiado')}}catch(e){}}
window.ownerToggleLock=async function(){try{const c=await ensureRuntime();const {error}=await c.rpc('fromago_secure_owner_lock',{p_room_id:roomId,p_owner_secret:ownerSecret,p_locked:!roomData.locked});if(error)throw error;await refreshRoom()}catch(e){toast(explain(e))}}
window.ownerKick=async function(pid,name){if(!confirm(`¿Expulsar y bloquear a ${name} en este grupo?`))return;try{const c=await ensureRuntime();const {error}=await c.rpc('fromago_secure_owner_remove_participant',{p_room_id:roomId,p_owner_secret:ownerSecret,p_participant_id:pid});if(error)throw error;await refreshRoom()}catch(e){toast(explain(e))}}
window.ownerRotateLink=async function(){if(!confirm('Se invalidará el enlace compartido actual. Los participantes que ya están dentro necesitarán el nuevo enlace si vuelven a cargar. ¿Continuar?'))return;try{const nk=rnd(),c=await ensureRuntime();const {error}=await c.rpc('fromago_secure_owner_rotate_invite',{p_room_id:roomId,p_owner_secret:ownerSecret,p_new_invite_secret:nk});if(error)throw error;const u=new URL(location.href);u.searchParams.set('k',nk);u.searchParams.set('appv','8');history.replaceState(null,'',u);location.reload()}catch(e){toast(explain(e))}}

// Override generic share text to respect the selected person's view.
itineraryText=function(){const arr=activeActivities();let lines=[`🧀 FROMAGO 2026 · ${viewLabel()}`],d='';for(const a of arr){if(a.day!==d){d=a.day;lines.push('',`— ${d} —`)}lines.push(`${a.time} · ${a.title} · ${a.location} · ${namesFor(a.id).join(', ')}`)}return lines.join('\n')}

const originalRenderProgram=renderProgram;
renderProgram=function(){originalRenderProgram();const app=document.getElementById('app');if(app)app.insertAdjacentHTML('afterbegin',secureNotice())}

async function boot(){try{await ensureRuntime();if(roomId&&inviteKey){await refreshRoom();pollTimer=setInterval(()=>{if(document.visibilityState==='visible')refreshRoom(true).then(()=>render())},5000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refreshRoom()})}else render()}catch(e){console.error(e);document.getElementById('app').innerHTML='<div class="empty">No se pudo iniciar la versión segura.</div>'}}
window.addEventListener('beforeunload',()=>{if(pollTimer)clearInterval(pollTimer)});
setupFilters();render();boot();
})();
